"""
This script contains all SQL statements used by the Sparkify Data Warehouse project.

Including:
- DROP TABLE statements
- CREATE TABLE statements
- COPY commands for staging tables
- INSERT statements for fact and dimension tables
- Query lists executed by the ETL scripts
"""

import configparser


# CONFIG
config = configparser.ConfigParser()
config.read('dwh.cfg')

LOG_DATA = config.get('S3', 'LOG_DATA')
SONG_DATA = config.get('S3', 'SONG_DATA')
LOG_JSONPATH = config.get('S3', 'LOG_JSONPATH')
ARN = config.get('IAM_ROLE', 'ARN')

# ---------------------------------------------------------------------
# DROP TABLE STATEMENTS
# ---------------------------------------------------------------------

staging_events_table_drop = "DROP TABLE IF EXISTS staging_events;"
staging_songs_table_drop = "DROP TABLE IF EXISTS staging_songs;"
songplay_table_drop = "DROP TABLE IF EXISTS songplays;"
user_table_drop = "DROP TABLE IF EXISTS users;"
song_table_drop = "DROP TABLE IF EXISTS songs;"
artist_table_drop = "DROP TABLE IF EXISTS artists;"
time_table_drop = "DROP TABLE IF EXISTS time;"

# ---------------------------------------------------------------------
# CREATE TABLE STATEMENTS
# ---------------------------------------------------------------------

staging_events_table_create= ("""
CREATE TABLE staging_events (
artist VARCHAR,
auth  VARCHAR,
firstName VARCHAR,
gender VARCHAR,
itemInSession INTEGER,
lastName VARCHAR,
length FLOAT,
level VARCHAR,
location VARCHAR,
method VARCHAR,
page VARCHAR,
registration FLOAT,
sessionId INTEGER,
song VARCHAR,
status INTEGER,
ts BIGINT,
userAgent VARCHAR,
userId VARCHAR
);
""")


staging_songs_table_create = (""" 
CREATE TABLE staging_songs (
num_songs INTEGER,
artist_id VARCHAR,
artist_latitude FLOAT,
artist_longitude FLOAT,
artist_location VARCHAR,
artist_name VARCHAR,
song_id VARCHAR, 
title VARCHAR,
duration FLOAT,
year INTEGER
);

""")

# Fact table containing song play events generated by users.
songplay_table_create = ("""
CREATE TABLE songplays (
songplay_id INTEGER IDENTITY(0,1) PRIMARY KEY,
start_time TIMESTAMP NOT NULL,
user_id INTEGER NOT NULL,
level VARCHAR,
song_id VARCHAR,
artist_id VARCHAR,
session_id INTEGER,
location VARCHAR,
user_agent VARCHAR
);
""")

# Dimension table containing user information.
user_table_create = ("""
CREATE TABLE users (
user_id INTEGER PRIMARY KEY,
first_name VARCHAR,
last_name VARCHAR,
gender VARCHAR,
level VARCHAR
);
""")

# Dimension table containing song metadata.
song_table_create = ("""
CREATE TABLE songs (
song_id VARCHAR PRIMARY KEY,
title VARCHAR,
artist_id VARCHAR,
year INTEGER,
duration FLOAT
);
""")

# Dimension table containing artist information.
artist_table_create = ("""
CREATE TABLE artists (
artist_id VARCHAR PRIMARY KEY,
name VARCHAR,
location VARCHAR,
latitude FLOAT,
longitude FLOAT
);
""")

# Dimension table containing time attributes derived from timestamps.
time_table_create = ("""
CREATE TABLE time (
start_time TIMESTAMP PRIMARY KEY,
hour INTEGER,
day INTEGER,
week INTEGER,
month INTEGER,
year INTEGER,
weekday INTEGER
);
""")

# ---------------------------------------------------------------------
# COPY COMMANDS FOR STAGING TABLES
# ---------------------------------------------------------------------

staging_events_copy = ("""
COPY staging_events 
FROM {}
IAM_ROLE {}
FORMAT AS JSON {}
REGION 'us-west-2';
""").format(LOG_DATA, ARN, LOG_JSONPATH)

staging_songs_copy = ("""
COPY staging_songs
FROM {}
IAM_ROLE {}
FORMAT AS JSON 'auto'
REGION 'us-west-2';
""").format(SONG_DATA, ARN)


# ---------------------------------------------------------------------
# INSERT STATEMENTS FOR ANALYTICS TABLES
# ---------------------------------------------------------------------

songplay_table_insert = ("""
INSERT INTO songplays (
    start_time,
    user_id,
    level,
    song_id,
    artist_id,
    session_id,
    location,
    user_agent
 )
 SELECT 
    TIMESTAMP 'epoch' + e.ts/1000 * INTERVAL '1 second' AS start_time,
    e.userId::INTEGER AS user_id,
    e.level,
    s.song_id,
    s.artist_id,
    e.sessionId,
    e.location,
    e.userAgent
 FROM staging_events e
 JOIN staging_songs s
     ON e.song = s.title
     AND e.artist = s.artist_name
     AND e.length = s.duration
 WHERE e.page = 'NextSong'
 AND e.userId IS NOT NULL
 AND e.userId <> '';
""")

user_table_insert = ("""
INSERT INTO users (
    user_id,
    first_name,
    last_name,
    gender,
    level
)
SELECT
    userId::INTEGER AS user_id,
    firstName AS first_name,
    lastName AS last_name,
    gender,
    level
FROM (
    SELECT
        userId,
        firstName,
        lastName,
        gender,
        level,
        ROW_NUMBER() OVER (
            PARTITION BY userId
            ORDER BY ts DESC
        ) AS row_num
    FROM staging_events
    WHERE userId IS NOT NULL
    AND userId <> ''
)
WHERE row_num = 1;
""")

song_table_insert = ("""
INSERT INTO songs (
        song_id,
        title,
        artist_id,
        year,
        duration
    )
SELECT DISTINCT
    song_id,
    title,
    artist_id,
    year,
    duration
FROM staging_songs
WHERE song_id IS NOT NULL;
""")

artist_table_insert = ("""
INSERT INTO artists (
    artist_id,
    name,
    location,
    latitude,
    longitude
)

SELECT DISTINCT
    artist_id,
    artist_name AS name,
    artist_location AS location,
    artist_latitude AS latitude,
    artist_longitude AS longitude
FROM staging_songs
WHERE artist_id IS NOT NULL;
""")

time_table_insert = ("""
INSERT INTO time (
    start_time,
    hour,
    day,
    week,
    month,
    year,
    weekday
)

SELECT DISTINCT
    start_time,
    EXTRACT(hour FROM start_time),
    EXTRACT(day FROM start_time),
    EXTRACT(week FROM start_time),
    EXTRACT(month FROM start_time),
    EXTRACT(year FROM start_time),
    EXTRACT(dayofweek FROM start_time)
FROM (
    SELECT
        TIMESTAMP 'epoch' + ts/1000 * INTERVAL '1 second' AS start_time
    FROM staging_events
    WHERE page = 'NextSong'

) AS t;
""")

# ---------------------------------------------------------------------
# QUERY LISTS
# ---------------------------------------------------------------------

create_table_queries = [staging_events_table_create, staging_songs_table_create, songplay_table_create, user_table_create, song_table_create, artist_table_create, time_table_create]
drop_table_queries = [staging_events_table_drop, staging_songs_table_drop, songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]
copy_table_queries = [staging_events_copy, staging_songs_copy]
insert_table_queries = [songplay_table_insert, user_table_insert, song_table_insert, artist_table_insert, time_table_insert]



